# Accela agency configs — extracted from old accela_scraper.py

ACCELA_CONFIGS = {
    "dallas": {
        "agency_code": "DALLASTX",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "detroit": {
        "agency_code": "DETROIT",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "charlotte": {
        "agency_code": "CHARLOTTE",
        "module": "LandDevelopment",
        "tab_name": "LandDevelopment",
        "search_url_path": "Cap/CapHome.aspx?module=LandDevelopment&TabName=LandDevelopment",
    },
    "reno": {
        "agency_code": "RENO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "indianapolis": {
        "agency_code": "INDY",
        "module": "Permits",
        "tab_name": "Permits",
        # Indianapolis uses "Permits and Contractors" tab on home, but module=Permits in URL
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "memphis": {
        "agency_code": "SHELBYCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "omaha": {
        "agency_code": "OMAHA",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "oklahoma_city": {
        "agency_code": "OKC",
        "module": "Permits",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=HOME",
        # OKC uses a custom Accela domain, not aca-prod.accela.com
        "base_url": "https://access.okc.gov/aca",
    },
    "oakland": {
        "agency_code": "OAKLAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lancaster_ca": {
        "agency_code": "LANCASTER",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "palmdale": {
        "agency_code": "PALMDALE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "milwaukee": {
        "agency_code": "MILWAUKEE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "stockton": {
        "agency_code": "STOCKTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santa_clarita": {
        "agency_code": "SANTACLARITA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fresno": {
        "agency_code": "FRESNO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fort_worth": {
        "agency_code": "CFW",
        "module": "Development",
        "tab_name": "Development",
        "search_url_path": "Cap/CapHome.aspx?module=Development&TabName=Development",
    },
    "san_diego": {
        "agency_code": "SANDIEGO",
        "module": "DSD",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=DSD&TabName=Home",
    },
    "anaheim": {
        "agency_code": "ANAHEIM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "colorado_springs": {
        "agency_code": "COSPRINGS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chula_vista": {
        "agency_code": "CHULAVISTA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Huntington Beach uses custom Accela domain
    "huntington_beach": {
        "agency_code": "HUNTINGTON_BEACH",
        "module": "Building",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
        "base_url": "https://engage.huntingtonbeachca.gov/CitizenAccess",
    },
    "virginia_beach": {
        "agency_code": "CVB",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "st_louis_county": {
        "agency_code": "SLC",
        "module": "Construction",
        "tab_name": "Construction",
        "search_url_path": "Cap/CapHome.aspx?module=Construction&TabName=Construction",
    },
    "chandler": {
        "agency_code": "CHANDLER",
        "module": "DevServices",
        "tab_name": "DevServices",
        "search_url_path": "Cap/CapHome.aspx?module=DevServices&TabName=DevServices",
    },
    # V35: New Accela cities
    "sacramento": {
        "agency_code": "SACRAMENTO",
        "module": "Building",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=HOME",
    },
    "atlanta": {
        "agency_code": "ATLANTA_GA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&customglobalsearch=true",
    },
    "dayton": {
        "agency_code": "DAYTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cleveland": {
        "agency_code": "COC",
        "module": "BuildingHousing",
        "tab_name": "BuildingHousing",
        "search_url_path": "Cap/CapHome.aspx?module=BuildingHousing&TabName=BuildingHousing",
    },
    "salt_lake_city": {
        "agency_code": "SLCREF",
        "module": "Building",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=HOME",
    },
    "brownsville_tx": {
        "agency_code": "BROWNSVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "clark_county_nv": {
        "agency_code": "CLARKCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lee_county_fl": {
        "agency_code": "LEECO",
        "module": "Permitting",
        "tab_name": "Permitting",
        "search_url_path": "Cap/CapHome.aspx?module=Permitting&TabName=Permitting",
    },
    "brevard_county_fl": {
        "agency_code": "BREVARD",
        "module": "Building",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=HOME",
    },
    "polk_county_fl": {
        "agency_code": "POLKCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pasco_county_fl": {
        "agency_code": "PASCO",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "sarasota_county_fl": {
        "agency_code": "SARASOTA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santa_clara_county": {
        "agency_code": "SCCGOV",
        "module": "Development",
        "tab_name": "Development",
        "search_url_path": "Cap/CapHome.aspx?module=Development&TabName=Development",
    },
    "bernalillo_county_nm": {
        "agency_code": "BERNCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "brookline_ma": {
        "agency_code": "BROOKLINE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "evanston_il": {
        "agency_code": "EVANSTON",
        "module": "Building",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=HOME",
    },
    # V35 batch 2: 23 new Accela portals found via web search
    "tampa_fl": {
        "agency_code": "TAMPA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hillsborough_county_fl": {
        "agency_code": "HCFL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pinellas_county_fl": {
        "agency_code": "PINELLAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fort_lauderdale_fl": {
        "agency_code": "FTL",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "gwinnett_county_ga": {
        "agency_code": "GWINNETT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_bernardino_county_ca": {
        "agency_code": "SBCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_antonio_tx": {
        "agency_code": "COSA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "denver_co": {
        "agency_code": "DENVER",
        "module": "Development",
        "tab_name": "Development",
        "search_url_path": "Cap/CapHome.aspx?module=Development&TabName=Development",
    },
    "contra_costa_county_ca": {
        "agency_code": "CCC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_mateo_county_ca": {
        "agency_code": "SMCGOV",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "arlington_county_va": {
        "agency_code": "ARLINGTONCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "anne_arundel_county_md": {
        "agency_code": "AACO",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "palo_alto_ca": {
        "agency_code": "PALOALTO",
        "module": "Building",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
    },
    "weld_county_co": {
        "agency_code": "WELD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "clackamas_county_or": {
        "agency_code": "CLACKAMAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fort_wayne_in": {
        "agency_code": "ACFW",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "grand_rapids_mi": {
        "agency_code": "GRANDRAPIDS",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "birmingham_al": {
        "agency_code": "BIRMINGHAM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "monterey_county_ca": {
        "agency_code": "MONTEREY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "alameda_ca": {
        "agency_code": "ALAMEDA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_leandro_ca": {
        "agency_code": "SANLEANDRO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "martin_county_fl": {
        "agency_code": "MARTINCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "citrus_county_fl": {
        "agency_code": "CITRUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "coweta_county_ga": {
        "agency_code": "COWETA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "deland_fl": {
        "agency_code": "DELAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "el_paso_tx": {
        "agency_code": "ELPASO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V35 batch 3
    "charlotte_county_fl": {
        "agency_code": "BOCC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "leon_county_fl": {
        "agency_code": "LEONCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pima_county_az": {
        "agency_code": "PIMA",
        "module": "Building",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
    },
    "queen_creek_az": {
        "agency_code": "QC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chesterfield_county_va": {
        "agency_code": "CHESTERFIELD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fairfax_va": {
        "agency_code": "FAIRFAX",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "loveland_co": {
        "agency_code": "LOVELAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "wichita": {
        "agency_code": "WICHITA",
        "module": "Engineering",
        "tab_name": "Engineering",
        "search_url_path": "Cap/CapHome.aspx?module=Engineering&TabName=Engineering",
    },
    "lexington_ky": {
        "agency_code": "LEXKY",
        "module": "Building",
        "tab_name": "Building Inspection",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building%20Inspection",
    },
    "lincoln": {
        "agency_code": "LINCOLN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: New county Accela portals
    "placer_county_ca": {
        "agency_code": "PLACERCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "washington_county_or": {
        "agency_code": "WASHCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://permits.washingtoncountyor.gov/CitizenAccess",
    },
    # V72: More CA cities with Accela
    "rancho_cucamonga": {
        "agency_code": "cityofrc",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "garden_grove": {
        "agency_code": "GG",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "corona": {
        "agency_code": "CORONA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fontana": {
        "agency_code": "FONTANA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "ontario_ca": {
        "agency_code": "ONTARIOCA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "moreno_valley": {
        "agency_code": "MOVAL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: More county/city Accela portals
    "kern_county_ca": {
        "agency_code": "KERNCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://accela.kerncounty.com/CitizenAccess",
    },
    "ventura_county_ca": {
        "agency_code": "VENTURA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://vcca.ventura.org",
    },
    "pharr_tx": {
        "agency_code": "PHARR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lexington_ky": {
        "agency_code": "LEXKY",
        "module": "Building",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
    },
    "charlotte_county_fl": {
        "agency_code": "CHARLOTTECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Ohio cities with Accela
    "toledo_oh": {
        "agency_code": "TOLEDO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://citizenaccess.toledo.oh.gov/CitizenAccess",
    },
    "columbus_oh": {
        "agency_code": "COLUMBUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://portal.columbus.gov/permits",
    },
    "cincinnati_oh": {
        "agency_code": "CINCINNATI",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: NC cities with Accela
    "high_point_nc": {
        "agency_code": "COHP",
        "module": "Construction",
        "tab_name": "Construction",
        "search_url_path": "Cap/CapHome.aspx?module=Construction&TabName=Construction",
    },
    "cabarrus_county_nc": {
        "agency_code": "CABARRUS",
        "module": "Permits",
        "tab_name": "HOME",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=HOME",
        "base_url": "https://citizenaccess.cabarruscounty.us/CitizenAccess",
    },
    # V72: Tennessee cities with Accela
    "knoxville_tn": {
        "agency_code": "KNOXVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Virginia cities with Accela
    "richmond_va": {
        "agency_code": "RICHMOND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Washington state cities with Accela
    "tacoma_wa": {
        "agency_code": "TACOMA",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "spokane_wa": {
        "agency_code": "SPOKANE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://aca.spokanepermits.org/CitizenAccess",
    },
    # V72: Minnesota cities with Accela
    "rochester_mn": {
        "agency_code": "ROCHESTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "olmsted_county_mn": {
        "agency_code": "OLMSTED",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Alabama counties with Accela
    "jefferson_county_al": {
        "agency_code": "JCCAL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://permits.jccal.org/citizenaccess",
    },
    # V72: Connecticut cities with Accela
    "hartford_ct": {
        "agency_code": "HARTFORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Iowa counties with Accela
    "polk_county_ia": {
        "agency_code": "POLKCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: New Mexico cities with Accela
    "las_cruces_nm": {
        "agency_code": "LASCRUCES",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72: Wisconsin cities with Accela
    "madison_wi": {
        "agency_code": "MADISON",
        "module": "Permitting",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Permitting&TabName=Home",
        "base_url": "https://elam.cityofmadison.com/CitizenAccess",
    },
    # V72: Kentucky cities with Accela
    "louisville_ky": {
        "agency_code": "LJCMG",
        "module": "Building",
        "tab_name": "Home",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
    },
    # V72: Massachusetts cities with Accela
    "springfield_ma": {
        "agency_code": "SPRINGFIELD_MA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://permits.springfieldcityhall.com/citizenaccess",
    },
    # V72 Batch 5: More Accela portals
    "fairfax_va": {
        "agency_code": "FAIRFAX",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mcallen_tx": {
        "agency_code": "MCALLEN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "manatee_county_fl": {
        "agency_code": "MANATEE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "osceola_county_fl": {
        "agency_code": "OSCEOLA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://permits.osceola.org",
    },
    "citrus_county_fl": {
        "agency_code": "CITRUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "merced_county_ca": {
        "agency_code": "MERCED",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chesterfield_county_va": {
        "agency_code": "CHESTERFIELD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "torrance_ca": {
        "agency_code": "TORRANCE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "deland_fl": {
        "agency_code": "DELAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "oregon_state": {
        "agency_code": "OREGON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://aca-oregon.accela.com/OREGON",
    },
    "el_paso_tx": {
        "agency_code": "ELPASO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "culver_city_ca": {
        "agency_code": "CULVERCITY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_joaquin_county_ca": {
        "agency_code": "SANJOAQUIN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pima_county_az": {
        "agency_code": "PIMA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "baltimore_county_md": {
        "agency_code": "BALTCO",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    # V72 Batch 6: More Accela portals
    "maricopa_county_az": {
        "agency_code": "MCOSS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://accela.maricopa.gov/CitizenAccessMCOSS",
    },
    "allegheny_county_pa": {
        "agency_code": "ALLEGHENY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cary_nc": {
        "agency_code": "CARY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "baton_rouge_la": {
        "agency_code": "EBR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "albany_ny": {
        "agency_code": "ALBANY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "montgomery_county_md": {
        "agency_code": "MOCO",
        "module": "DPS",
        "tab_name": "DPS",
        "search_url_path": "Cap/CapHome.aspx?module=DPS&TabName=DPS",
    },
    "prince_william_county_va": {
        "agency_code": "PWC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "loudoun_county_va": {
        "agency_code": "LOUDOUN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "henrico_county_va": {
        "agency_code": "HENRICO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "volusia_county_fl": {
        "agency_code": "VOLUSIA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "seminole_county_fl": {  # Legacy key - kept for backwards compatibility
        "agency_code": "SEMINOLECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "seminoleco": {  # V73: Fixed - was SEMINOLE but that endpoint is now dead
        "agency_code": "SEMINOLECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "orange_county_fl": {
        "agency_code": "ORANGECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "palm_beach_county_fl": {
        "agency_code": "PBC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "broward_county_fl": {
        "agency_code": "BROWARD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "duval_county_fl": {
        "agency_code": "DUVAL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72 Batch 7: More NY and other state cities
    # V74: rochester_ny config moved to V74 section with correct agency_code "ROCHESTER"
    "nyc_dob": {
        "agency_code": "NYCDOB",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://a810-lmpaca.nyc.gov/citizenaccessbuildings",
    },
    "westchester_county_ny": {
        "agency_code": "WESTCHESTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "nassau_county_ny": {
        "agency_code": "NASSAU",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "suffolk_county_ny": {
        "agency_code": "SUFFOLK",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # PA cities
    "philadelphia_pa": {
        "agency_code": "PHILA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pittsburgh_pa": {
        "agency_code": "PGHPA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "bucks_county_pa": {
        "agency_code": "BUCKS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "montgomery_county_pa": {
        "agency_code": "MONTCOPA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "delaware_county_pa": {
        "agency_code": "DELCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # MI cities
    "grand_rapids_mi": {
        "agency_code": "GR",
        "module": "Permits",
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "ann_arbor_mi": {
        "agency_code": "ANNARBOR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "warren_mi": {
        "agency_code": "WARREN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "sterling_heights_mi": {
        "agency_code": "STERLING",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "wayne_county_mi": {
        "agency_code": "WAYNECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "oakland_county_mi": {
        "agency_code": "OAKLANDCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # More IN cities
    "south_bend_in": {
        "agency_code": "SBEND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "evansville_in": {
        "agency_code": "EVANSVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hamilton_county_in": {
        "agency_code": "HAMILTONIN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72 Batch 8: More CO and GA cities/counties
    "boulder_county_co": {
        "agency_code": "BOCO",
        "module": "Planning",
        "tab_name": "Planning",
        "search_url_path": "Cap/CapHome.aspx?module=Planning&TabName=Planning",
        "base_url": "https://accelapublic.bouldercounty.org/CitizenAccess",
    },
    "longmont_co": {
        "agency_code": "LONGMONT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://aca.longmontcolorado.gov/CitizenAccess",
    },
    "fort_collins_co": {
        "agency_code": "FTCOLLINS",
        "module": "Planning",
        "tab_name": "Planning",
        "search_url_path": "Cap/CapHome.aspx?module=Planning&TabName=Planning",
        "base_url": "https://accela-aca.fcgov.com/CitizenAccess",
    },
    "clayton_county_ga": {
        "agency_code": "CLAYTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cobb_county_ga": {  # Legacy key - kept for backwards compatibility
        "agency_code": "COBBCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cobbco": {  # V73: Fixed - was COBB but that endpoint is now 404
        "agency_code": "COBBCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fulton_county_ga": {
        "agency_code": "FULTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "dekalb_county_ga": {
        "agency_code": "DEKALB",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "jackson_county_or": {
        "agency_code": "JACKSON_CO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://aca-oregon.accela.com/jackson_co",
    },
    "tigard_or": {
        "agency_code": "TIGARD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "albany_or": {
        "agency_code": "ALBANY_OR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # More SC and NC counties
    "greenville_county_sc": {
        "agency_code": "GREENVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "charleston_county_sc": {
        "agency_code": "CHARLESTON_SC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "wake_county_nc": {
        "agency_code": "WAKE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mecklenburg_county_nc": {
        "agency_code": "MECKLENBURG",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "guilford_county_nc": {
        "agency_code": "GUILFORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "forsyth_county_nc": {
        "agency_code": "FORSYTH",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V72 Batch 9: More CA Bay Area cities
    "walnut_creek_ca": {
        "agency_code": "WC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "concord_ca": {
        "agency_code": "CONCORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santa_clara_city_ca": {
        "agency_code": "SANTACLARA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Home",
    },
    "pittsburg_ca": {
        "agency_code": "PITTSBURG",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lincoln_ne": {
        "agency_code": "LINCOLN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://permits.lincoln.ne.gov/CitizenAccess",
    },
    "shelby_county_tn": {
        "agency_code": "SHELBYCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "st_louis_county_mo": {
        "agency_code": "SLC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "tos": {  # V73: Fixed - was sahuarita_az with wrong agency code
        "agency_code": "TOS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "queen_creek_az": {
        "agency_code": "QC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "peoria_az": {
        "agency_code": "PEORIA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://devservices.peoriaaz.gov/devservices",
    },
    "goodyear_az": {
        "agency_code": "GOODYEAR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: New Accela cities
    "visalia": {
        "agency_code": "VISALIA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "inglewood": {
        "agency_code": "INGLEWOOD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "downey": {
        "agency_code": "DOWNEY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "berkeley": {
        "agency_code": "BERKELEY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "torrance": {
        "agency_code": "TORRANCE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fontana": {
        "agency_code": "FONTANA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "richmond_ca": {
        "agency_code": "RICHMOND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "concord_ca": {
        "agency_code": "CONCORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "knoxville": {
        "agency_code": "KNOXVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chesapeake_va": {
        "agency_code": "CHESAPEAKE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "tampa": {
        "agency_code": "TAMPA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hollywood_fl": {
        "agency_code": "HOLLYWOOD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "san_leandro": {
        "agency_code": "SANLEANDRO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "fort_lauderdale": {
        "agency_code": "FTLAUDERDALE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "wichita": {
        "agency_code": "WICHITA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "grand_rapids": {
        "agency_code": "GR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
        "base_url": "https://inspections.grcity.us/CitizenAccess",
    },
    "alameda": {
        "agency_code": "ALAMEDA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pleasanton": {
        "agency_code": "PLEASANTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "livermore": {
        "agency_code": "LIVERMORE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pittsburg": {
        "agency_code": "PITTSBURG",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hollister": {
        "agency_code": "HOLLISTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "monterey": {
        "agency_code": "MONTEREY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "menlo_park": {
        "agency_code": "MENLOPARK",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "sparks": {
        "agency_code": "SPARKS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "corvallis": {
        "agency_code": "CORVALLIS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "tigard": {
        "agency_code": "TIGARD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 4 - Major cities
    "baltimore": {
        "agency_code": "BALTIMORE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "bradenton": {
        "agency_code": "BRADENTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hillsboro": {
        "agency_code": "HILLSBORO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lincoln": {
        "agency_code": "LINCOLN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mesa": {
        "agency_code": "MESA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santaana": {
        "agency_code": "SANTAANA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santabarbara": {
        "agency_code": "SANTABARBARA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "scottsdale": {
        "agency_code": "SCOTTSDALE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "whittier": {
        "agency_code": "WHITTIER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "yuba": {
        "agency_code": "YUBA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 5 - Counties and mid-size cities
    "anaheim": {
        "agency_code": "ANAHEIM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "anchorage": {
        "agency_code": "ANCHORAGE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "boise": {
        "agency_code": "BOISE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "citrus": {
        "agency_code": "CITRUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "elkgrove": {
        "agency_code": "ELKGROVE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "martinez": {
        "agency_code": "MARTINEZ",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "meridian": {
        "agency_code": "MERIDIAN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "missoula": {
        "agency_code": "MISSOULA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "ojai": {
        "agency_code": "OJAI",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "paradise": {
        "agency_code": "PARADISE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "sanbenito": {
        "agency_code": "SANBENITO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "sandimas": {
        "agency_code": "SANDIMAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "snohomish": {
        "agency_code": "SNOHOMISH",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "solano": {
        "agency_code": "SOLANO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "westsac": {
        "agency_code": "WESTSAC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "yorbalinda": {
        "agency_code": "YORBALINDA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 6
    "brenham": {
        "agency_code": "BRENHAM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "galveston": {
        "agency_code": "GALVESTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "weston": {
        "agency_code": "WESTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "kettering": {
        "agency_code": "KETTERING",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 7
    "brea": {
        "agency_code": "BREA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chino": {
        "agency_code": "CHINO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hopkinsville": {
        "agency_code": "HOPKINSVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 8
    "andover": {
        "agency_code": "ANDOVER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "avondale": {
        "agency_code": "AVONDALE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chesterfield": {
        "agency_code": "CHESTERFIELD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 9
    "keybiscayne": {
        "agency_code": "KEYBISCAYNE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mansfield": {
        "agency_code": "MANSFIELD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mendocino": {
        "agency_code": "MENDOCINO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "montgomery": {
        "agency_code": "MONTGOMERY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mulberry": {
        "agency_code": "MULBERRY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 10
    "northport": {
        "agency_code": "NORTHPORT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "papillion": {
        "agency_code": "PAPILLION",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pasco": {
        "agency_code": "PASCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pinal": {
        "agency_code": "PINAL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pinehurst": {
        "agency_code": "PINEHURST",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "portchester": {
        "agency_code": "PORTCHESTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 11
    "ramsey": {
        "agency_code": "RAMSEY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santarosa": {
        "agency_code": "SANTAROSA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "socorro": {
        "agency_code": "SOCORRO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 12
    "tacoma": {
        "agency_code": "TACOMA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "tehachapi": {
        "agency_code": "TEHACHAPI",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "torrance": {
        "agency_code": "TORRANCE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "trinity": {
        "agency_code": "TRINITY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "westport": {
        "agency_code": "WESTPORT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "woodinville": {
        "agency_code": "WOODINVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 13
    "berkeley": {
        "agency_code": "BERKELEY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "bethany": {
        "agency_code": "BETHANY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "birmingham": {
        "agency_code": "BIRMINGHAM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "brevard": {
        "agency_code": "BREVARD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Missing configs fix
    "concord_nc": {
        "agency_code": "CONCORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "manteca": {
        "agency_code": "MANTECA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cupertino": {
        "agency_code": "CUPERTINO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "menlopark": {
        "agency_code": "MENLOPARK",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Fix missing configs
    "cosprings": {
        "agency_code": "COSPRINGS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chulavista": {
        "agency_code": "CHULAVISTA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lincoln": {
        "agency_code": "LINCOLN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "wichita": {
        "agency_code": "WICHITA",
        "module": "Engineering",
        "tab_name": "Engineering",
        "search_url_path": "Cap/CapHome.aspx?module=Engineering&TabName=Engineering",
    },
    # V73: Batch 14 - new counties
    "arapahoe": {
        "agency_code": "ARAPAHOE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "clearwater": {
        "agency_code": "CLEARWATER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "washoe": {
        "agency_code": "WASHOE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "douglas": {
        "agency_code": "DOUGLAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: Batch 16 - new cities
    "cof": {
        "agency_code": "COF",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cor": {
        "agency_code": "COR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: New Accela cities (8 new)
    "perris": {
        "agency_code": "PERRIS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "menifee": {
        "agency_code": "MENIFEE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "paloalto": {
        "agency_code": "PALOALTO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "santaclara": {
        "agency_code": "SANTACLARA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hollywood": {
        "agency_code": "HOLLYWOOD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "brownsville": {
        "agency_code": "BROWNSVILLE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pharr": {
        "agency_code": "PHARR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "clarkco": {
        "agency_code": "CLARKCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lancaster": {
        "agency_code": "LANCASTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "nogales": {
        "agency_code": "NOGALES",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "slc": {
        "agency_code": "SLC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "loveland": {
        "agency_code": "LOVELAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "longmont": {
        "agency_code": "LONGMONT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Southern US Accela (batch 3)
    "concord": {
        "agency_code": "CONCORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "mecklenburg": {
        "agency_code": "MECKLENBURG",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "columbus_ga": {
        "agency_code": "COLUMBUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "madison_al": {
        "agency_code": "MADISON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "franklin_tn": {
        "agency_code": "FRANKLIN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 4 (5 new)
    "richmond_tx": {
        "agency_code": "RICHMOND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "deland": {
        "agency_code": "DELAND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "grandrapids": {
        "agency_code": "GRANDRAPIDS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "rochester_mi": {
        "agency_code": "ROCHESTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "goodyear": {
        "agency_code": "GOODYEAR",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 5 - CA counties + VA/OR (7 new)
    "sonomaco": {
        "agency_code": "SONOMACO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "solanoco": {
        "agency_code": "SOLANOCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "butteco": {
        "agency_code": "BUTTECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "chesapeake": {
        "agency_code": "CHESAPEAKE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "placerco": {
        "agency_code": "PLACERCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "kernco": {
        "agency_code": "KERNCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "albany_or": {
        "agency_code": "ALBANY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 6 - FL/GA counties + CA (5 new)
    "nassau": {
        "agency_code": "NASSAU",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "pinellas": {
        "agency_code": "PINELLAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "coweta": {
        "agency_code": "COWETA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "gwinnett": {
        "agency_code": "GWINNETT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "tulareco": {
        "agency_code": "TULARECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 7
    "osceola": {
        "agency_code": "OSCEOLA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 8 - CO/NM/MN
    "golden": {
        "agency_code": "GOLDEN",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lascruces": {
        "agency_code": "LASCRUCES",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "maplewood": {
        "agency_code": "MAPLEWOOD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 9 - OH/IL/CT
    "cincinnati": {
        "agency_code": "CINCINNATI",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "evanston": {
        "agency_code": "EVANSTON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hartford": {
        "agency_code": "HARTFORD",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 10
    "elpaso": {
        "agency_code": "ELPASO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 11 - 7 new jurisdictions
    "columbus_oh": {
        "agency_code": "COLUMBUS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "humboldt": {
        "agency_code": "HUMBOLDT",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "kansas": {
        "agency_code": "KANSAS",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "madison_wi": {
        "agency_code": "MADISON",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "manatee": {
        "agency_code": "MANATEE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "richmond_va": {
        "agency_code": "RICHMOND",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "rochester_ny": {
        "agency_code": "ROCHESTER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 12
    "dallastx": {
        "agency_code": "DALLASTX",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V74: Accela batch 13 - Counties
    "adamsco": {
        "agency_code": "ADAMSCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hamiltoncounty": {
        "agency_code": "HAMILTONCOUNTY",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lakeco": {
        "agency_code": "LAKECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "shelbyco": {
        "agency_code": "SHELBYCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # V73: New Accela counties (batch 17)
    "kingco": {
        "agency_code": "KINGCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "sbco": {
        "agency_code": "SBCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "cooper": {
        "agency_code": "COOPER",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "lakeco": {
        "agency_code": "LAKECO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "hull": {
        "agency_code": "HULL",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "plum": {
        "agency_code": "PLUM",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "nogales": {
        "agency_code": "NOGALES",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "dupage": {
        "agency_code": "DUPAGE",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "adamsco": {
        "agency_code": "ADAMSCO",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },

    # V188: New configs for previously-unconfigured Accela cities
    # NO_AGENCY cities (discovered in Task 0 research)
    "santa_barbara": {
        "agency_code": "SANTABARBARA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "yorba_linda": {
        "agency_code": "YORBALINDA",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "west_sacramento": {
        "agency_code": "WESTSAC",
        "module": "Building",
        "tab_name": "Building",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    # Custom-URL portals (not on aca-prod.accela.com)
    "thousand_oaks": {
        "agency_code": "VENTURA",
        "module": "Building",
        "tab_name": "Building",
        "base_url": "https://vcca.ventura.org",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "camarillo": {
        "agency_code": "VENTURA",
        "module": "Building",
        "tab_name": "Building",
        "base_url": "https://vcca.ventura.org",
        "search_url_path": "Cap/CapHome.aspx?module=Building&TabName=Building",
    },
    "kannapolis": {
        "agency_code": "CABARRUS",
        "module": "Permits",
        "tab_name": "Permits",
        "base_url": "https://citizenaccess.cabarruscounty.us/CitizenAccess",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    # NO_RESULTS cities — try alternate modules
    "chula_vista": {
        "agency_code": "CHULAVISTA",
        "module": "Permits",  # Was Building, try Permits
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "columbus_ga": {
        "agency_code": "COLUMBUS",
        "module": "Permits",  # Was Building, try Permits
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "madison_al": {
        "agency_code": "MADISON",
        "module": "Permits",  # Was Building, try Permits
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },
    "tigard_or": {
        "agency_code": "TIGARD",
        "module": "Permits",  # Was Building, try Permits
        "tab_name": "Permits",
        "search_url_path": "Cap/CapHome.aspx?module=Permits&TabName=Permits",
    },

}

# V161 deploy trigger
