"""
PermitGrab - Modular City Configuration System
Each city is a configuration entry with platform-specific settings.
Supports: Socrata (SODA API), ArcGIS REST, CKAN, CARTO
"""

from datetime import datetime, timedelta

# ============================================================================
# CITY REGISTRY - All cities and their API configurations
# ============================================================================
# Each city config entry contains:
#   - name: Display name
#   - state: 2-letter state code
#   - slug: URL-safe city identifier
#   - platform: "socrata" | "arcgis" | "ckan" | "carto"
#   - endpoint: Full API endpoint URL
#   - dataset_id: Dataset identifier (for reference/debugging)
#   - field_map: Maps our standard fields to source API fields
#   - date_field: Field used for date filtering
#   - date_format: "iso" (default), "epoch", "none"
#   - active: Whether to include in collection
#   - notes: Any special notes about this source

CITY_REGISTRY = {
    # =========================================================================
    # SOCRATA PLATFORM CITIES (SODA API)
    # =========================================================================

    "new_york": {
        "name": "New York City",
        "state": "NY",
        "slug": "new-york",
        "platform": "socrata",
        "endpoint": "https://data.cityofnewyork.us/resource/rbx6-tga4.json",
        "dataset_id": "rbx6-tga4",
        "description": "DOB NOW: Build - Approved Permits",
        "field_map": {
            "permit_number": "job_filing_number",
            "permit_type": "work_type",
            "work_type": "work_type",
            "address": "house_no",
            "street": "street_name",
            "borough": "borough",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "filing_date": "issued_date",
            "status": "permit_status",
            "estimated_cost": "estimated_job_costs",
            "description": "job_description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "chicago": {
        "name": "Chicago",
        "state": "IL",
        "slug": "chicago",
        "platform": "socrata",
        "endpoint": "https://data.cityofchicago.org/resource/ydr8-5enu.json",
        "dataset_id": "ydr8-5enu",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_",
            "permit_type": "permit_type",
            "work_type": "work_description",
            "address": "street_number",
            "street": "street_direction",
            "street_name": "street_name",
            "zip": "zip_code",
            "contact_name": "contact_1_name",
            "contact_phone": "contact_1_city",
            "filing_date": "issue_date",
            "status": "permit_status",
            "estimated_cost": "reported_cost",
            "description": "work_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "los_angeles": {
        "name": "Los Angeles",
        "state": "CA",
        "slug": "los-angeles",
        "platform": "socrata",
        "endpoint": "https://data.lacity.org/resource/pi9x-tg5x.json",
        "dataset_id": "pi9x-tg5x",
        "description": "Building and Safety - Building Permits Issued from 2020 to Present",
        "field_map": {
            "permit_number": "permit_nbr",
            "permit_type": "permit_type",
            "permit_sub_type": "permit_sub_type",
            "work_type": "work_desc",
            "address": "primary_address",
            "zip": "zip_code",
            "filing_date": "issue_date",
            "status": "status_desc",
            "estimated_cost": "valuation",
            "description": "work_desc",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "austin": {
        "name": "Austin",
        "state": "TX",
        "slug": "austin",
        "platform": "socrata",
        "endpoint": "https://data.austintexas.gov/resource/3syk-w9eu.json",
        "dataset_id": "3syk-w9eu",
        "description": "Issued Construction Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type_desc",
            "work_type": "work_class",
            "address": "original_address1",
            "filing_date": "issue_date",
            "status": "status_current",
            "estimated_cost": "",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "san_francisco": {
        "name": "San Francisco",
        "state": "CA",
        "slug": "san-francisco",
        "platform": "socrata",
        "endpoint": "https://data.sfgov.org/resource/i98e-djp9.json",
        "dataset_id": "i98e-djp9",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type_definition",
            "work_type": "proposed_use",
            "address": "street_number",
            "street": "street_name",
            "zip": "zipcode",
            "filing_date": "filed_date",
            "status": "status",
            "estimated_cost": "estimated_cost",
            "description": "description",
        },
        "date_field": "filed_date",
        "limit": 2000,
        "active": True,
    },

    "seattle": {
        "name": "Seattle",
        "state": "WA",
        "slug": "seattle",
        "platform": "socrata",
        "endpoint": "https://data.seattle.gov/resource/76t5-zqzr.json",
        "dataset_id": "76t5-zqzr",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "permitclass",
            "work_type": "permitclassmapped",
            "address": "originaladdress1",
            "filing_date": "issueddate",
            "status": "statuscurrent",
            "estimated_cost": "",
            "description": "description",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "new_orleans": {
        "name": "New Orleans",
        "state": "LA",
        "slug": "new-orleans",
        "platform": "socrata",
        "endpoint": "https://data.nola.gov/resource/rcm3-fn58.json",
        "dataset_id": "rcm3-fn58",
        "description": "Permits",
        "field_map": {
            "permit_number": "numstring",
            "permit_type": "type",
            "work_type": "code",
            "address": "address",
            "zip": "",
            "owner_name": "owner",
            "contact_name": "applicant",
            "filing_date": "issuedate",
            "status": "currentstatus",
            "estimated_cost": "constrval",
            "description": "description",
        },
        "date_field": "issuedate",
        "limit": 2000,
        "active": True,
    },

    "baton_rouge": {
        "name": "Baton Rouge",
        "state": "LA",
        "slug": "baton-rouge",
        "platform": "socrata",
        "endpoint": "https://data.brla.gov/resource/f3qw-nd5k.json",
        "dataset_id": "f3qw-nd5k",
        "description": "EBR Building Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "permittype",
            "work_type": "designation",
            "address": "streetaddress",
            "zip": "zip",
            "contact_name": "contractorname",
            "filing_date": "issueddate",
            "status": "",
            "estimated_cost": "projectvalue",
            "description": "projectdescription",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "cincinnati": {
        "name": "Cincinnati",
        "state": "OH",
        "slug": "cincinnati",
        "platform": "socrata",
        "endpoint": "https://data.cincinnati-oh.gov/resource/cfkj-xb9y.json",
        "dataset_id": "cfkj-xb9y",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "permittype",
            "work_type": "workclass",
            "address": "originaladdress1",
            "zip": "originalzip",
            "filing_date": "issueddate",
            "status": "statuscurrent",
            "estimated_cost": "estprojectcostdec",
            "description": "description",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    # NEW SOCRATA CITIES

    "cambridge": {
        "name": "Cambridge",
        "state": "MA",
        "slug": "cambridge",
        "platform": "socrata",
        "endpoint": "https://data.cambridgema.gov/resource/9qm7-wbdc.json",
        "dataset_id": "9qm7-wbdc",
        "description": "Building Permits: New Construction",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "estimated_cost",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "Field mapping needs verification",
    },

    "washington_dc": {
        "name": "Washington DC",
        "state": "DC",
        "slug": "washington-dc",
        "platform": "socrata",
        "endpoint": "https://opendata.dc.gov/resource/awax-vqek.json",
        "dataset_id": "awax-vqek",
        "description": "Building Permits - 2024",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_subtype",
            "address": "full_address",
            "zip": "zip",
            "owner_name": "owner_name",
            "contact_name": "applicant",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "fees_paid",
            "description": "description_of_work",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "Dataset ID needs verification",
    },

    "san_antonio": {
        "name": "San Antonio",
        "state": "TX",
        "slug": "san-antonio",
        "platform": "socrata",
        "endpoint": "https://data.sanantonio.gov/resource/v23u-v49r.json",
        "dataset_id": "v23u-v49r",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_class",
            "address": "site_address",
            "zip": "zip_code",
            "filing_date": "issue_date",
            "status": "permit_status",
            "estimated_cost": "valuation",
            "description": "project_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "404 - Dataset ID needs verification",
    },

    "kansas_city": {
        "name": "Kansas City",
        "state": "MO",
        "slug": "kansas-city",
        "platform": "socrata",
        "endpoint": "https://data.kcmo.org/resource/ue52-x8g8.json",
        "dataset_id": "ue52-x8g8",
        "description": "Permits - Core Dataset",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "job_value",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "403 Forbidden - May require app token",
    },

    "detroit": {
        "name": "Detroit",
        "state": "MI",
        "slug": "detroit",
        "platform": "socrata",
        "endpoint": "https://data.detroitmi.gov/resource/xw2a-a7tf.json",
        "dataset_id": "xw2a-a7tf",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_no",
            "permit_type": "permit_type",
            "work_type": "bld_type_use",
            "address": "site_address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "permit_issued",
            "status": "permit_status",
            "estimated_cost": "permit_value",
            "description": "work_description",
        },
        "date_field": "permit_issued",
        "limit": 2000,
        "active": False,
        "notes": "Dataset ID needs verification",
    },

    "pittsburgh": {
        "name": "Pittsburgh",
        "state": "PA",
        "slug": "pittsburgh",
        "platform": "socrata",
        "endpoint": "https://data.wprdc.org/resource/p7jk-dqfa.json",
        "dataset_id": "p7jk-dqfa",
        "description": "City of Pittsburgh Building Permits",
        "field_map": {
            "permit_number": "permit_id",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "total_project_value",
            "description": "work_desc",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "404 - Dataset ID needs verification",
    },

    "denver": {
        "name": "Denver",
        "state": "CO",
        "slug": "denver",
        "platform": "socrata",
        "endpoint": "https://data.denvergov.org/resource/75gn-3pb7.json",
        "dataset_id": "75gn-3pb7",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_class",
            "address": "full_address",
            "zip": "zip_code",
            "filing_date": "issue_date",
            "status": "status_current",
            "estimated_cost": "valuation",
            "description": "work_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": False,
        "notes": "Dataset ID needs verification",
    },

    "portland": {
        "name": "Portland",
        "state": "OR",
        "slug": "portland",
        "platform": "arcgis",
        "endpoint": "https://services.arcgis.com/quVN97tn06YNGj9s/arcgis/rest/services/Residential_Building_Permits/FeatureServer/0/query",
        "dataset_id": "Residential_Building_Permits",
        "description": "Residential Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_TYPE",
            "address": "ADDRESS",
            "zip": "ZIP",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # ARCGIS PLATFORM CITIES
    # =========================================================================

    "atlanta": {
        "name": "Atlanta",
        "state": "GA",
        "slug": "atlanta",
        "platform": "arcgis",
        "endpoint": "https://services5.arcgis.com/5RxyIIJ9boPdptdo/arcgis/rest/services/Building_Permit_latest/FeatureServer/0/query",
        "dataset_id": "Building_Permit_latest",
        "description": "Building Permits (2019-Present)",
        "field_map": {
            "permit_number": "RecordID",
            "permit_type": "TypeCombo",
            "work_type": "Subtype",
            "address": "Address",
            "zip": "",
            "filing_date": "Opend",
            "status": "Status_1",
            "estimated_cost": "JobValue",
            "description": "Name",
        },
        "date_field": "Opend",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "nashville": {
        "name": "Nashville",
        "state": "TN",
        "slug": "nashville",
        "platform": "arcgis",
        "endpoint": "https://services2.arcgis.com/HdTo6HJqh92wn4D8/arcgis/rest/services/Building_Permit_Applications_Feature_Layer_view/FeatureServer/0/query",
        "dataset_id": "Building_Permit_Applications",
        "description": "Building Permit Applications",
        "field_map": {
            "permit_number": "Permit__",
            "permit_type": "Permit_Type_Description",
            "work_type": "Permit_Subtype_Description",
            "address": "Address",
            "zip": "ZIP",
            "contact_name": "Contact",
            "filing_date": "Date_Entered",
            "status": "",
            "estimated_cost": "Const_Cost",
            "description": "Purpose",
        },
        "date_field": "Date_Entered",
        "date_format": "none",  # Fetch all, filter in Python
        "limit": 2000,
        "active": True,
    },

    "miami_dade": {
        "name": "Miami-Dade County",
        "state": "FL",
        "slug": "miami",
        "platform": "arcgis",
        "endpoint": "https://gis.miamidade.gov/arcgis/rest/services/MD_OpenData/MapServer/2/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits Issued",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PROC_DESC",
            "work_type": "PROC_DESC",
            "address": "ADDRESS",
            "zip": "ZIP",
            "contact_name": "APPL_NAME",
            "filing_date": "ISSUED_DATE",
            "status": "STATUS_DESC",
            "estimated_cost": "EST_COST",
            "description": "PROC_DESC",
        },
        "date_field": "ISSUED_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "raleigh": {
        "name": "Raleigh",
        "state": "NC",
        "slug": "raleigh",
        "platform": "arcgis",
        "endpoint": "https://services.arcgis.com/v400IkDOw1ad7Yad/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "SITE_ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUED_DATE",
            "status": "STATUS",
            "estimated_cost": "TOTAL_SQFT",
            "description": "PROJECT_NAME",
        },
        "date_field": "ISSUED_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "phoenix": {
        "name": "Phoenix",
        "state": "AZ",
        "slug": "phoenix",
        "platform": "arcgis",
        "endpoint": "https://services2.arcgis.com/2t1927381mhTgWNC/arcgis/rest/services/Bldg_Permits/FeatureServer/0/query",
        "dataset_id": "Bldg_Permits",
        "description": "Building Permit Data",
        "field_map": {
            "permit_number": "PERMIT_NO",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "WORK_DESC",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "san_jose": {
        "name": "San Jose",
        "state": "CA",
        "slug": "san-jose",
        "platform": "arcgis",
        "endpoint": "https://geo.sanjoseca.gov/server/rest/services/PLN/PLN_BuildingPermits/FeatureServer/0/query",
        "dataset_id": "PLN_BuildingPermits",
        "description": "Active Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER",
            "contact_name": "CONTRACTOR",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "san_diego": {
        "name": "San Diego",
        "state": "CA",
        "slug": "san-diego",
        "platform": "socrata",
        "endpoint": "https://data.sandiego.gov/resource/nq97-icrc.json",
        "dataset_id": "nq97-icrc",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "approval_id",
            "permit_type": "approval_type",
            "work_type": "project_scope",
            "address": "street_address",
            "zip": "zip_code",
            "filing_date": "approval_issue_date",
            "status": "status",
            "estimated_cost": "total_existing_bldg_sq_ft",
            "description": "project_title",
        },
        "date_field": "approval_issue_date",
        "limit": 2000,
        "active": True,
    },

    "sacramento": {
        "name": "Sacramento",
        "state": "CA",
        "slug": "sacramento",
        "platform": "arcgis",
        "endpoint": "https://services5.arcgis.com/54falWtcpty3V47Z/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Issued Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_TYPE",
            "address": "ADDRESS",
            "zip": "ZIP",
            "owner_name": "OWNER",
            "contact_name": "CONTRACTOR",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "PROJECT_DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # CKAN PLATFORM CITIES
    # =========================================================================

    "boston": {
        "name": "Boston",
        "state": "MA",
        "slug": "boston",
        "platform": "ckan",
        "endpoint": "https://data.boston.gov/api/3/action/datastore_search",
        "dataset_id": "6ddcd912-32a0-43df-9908-63574f8c7e77",
        "description": "Approved Building Permits",
        "field_map": {
            "permit_number": "PermitNumber",
            "permit_type": "PERMITTYPEDESCR",
            "work_type": "WORKTYPE",
            "address": "ADDRESS",
            "zip": "ZIP",
            "owner_name": "OWNER",
            "contact_name": "APPLICANT",
            "filing_date": "ISSUED_DATE",
            "status": "STATUS",
            "estimated_cost": "TOTAL_FEES",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUED_DATE",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # CARTO PLATFORM CITIES
    # =========================================================================

    "philadelphia": {
        "name": "Philadelphia",
        "state": "PA",
        "slug": "philadelphia",
        "platform": "carto",
        "endpoint": "https://phl.carto.com/api/v2/sql",
        "table_name": "li_permits",
        "dataset_id": "li_permits",
        "description": "L&I Building and Zoning Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "permittype",
            "work_type": "typeofwork",
            "address": "address",
            "zip": "zip",
            "owner_name": "opa_owner",
            "contact_name": "contractorname",
            "filing_date": "permitissuedate",
            "status": "status",
            "estimated_cost": "",
            "description": "typeofwork",
        },
        "date_field": "permitissuedate",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # ADDITIONAL SOCRATA CITIES (BATCH 2)
    # =========================================================================

    "baltimore": {
        "name": "Baltimore",
        "state": "MD",
        "slug": "baltimore",
        "platform": "socrata",
        "endpoint": "https://data.baltimorecity.gov/resource/fesm-tgxf.json",
        "dataset_id": "fesm-tgxf",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "use_code",
            "address": "street_address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "filing_date": "issue_date",
            "status": "permit_status",
            "estimated_cost": "cost_estimate",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "charlotte": {
        "name": "Charlotte",
        "state": "NC",
        "slug": "charlotte",
        "platform": "socrata",
        "endpoint": "https://data.charlottenc.gov/resource/vbgw-dnis.json",
        "dataset_id": "vbgw-dnis",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_num",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "site_address",
            "zip": "zip_code",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "project_cost",
            "description": "work_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "columbus": {
        "name": "Columbus",
        "state": "OH",
        "slug": "columbus",
        "platform": "socrata",
        "endpoint": "https://data.columbus.gov/resource/ki6q-vf3w.json",
        "dataset_id": "ki6q-vf3w",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "fort_worth": {
        "name": "Fort Worth",
        "state": "TX",
        "slug": "fort-worth",
        "platform": "socrata",
        "endpoint": "https://data.fortworthtexas.gov/resource/vr6t-77z3.json",
        "dataset_id": "vr6t-77z3",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "site_address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "work_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "honolulu": {
        "name": "Honolulu",
        "state": "HI",
        "slug": "honolulu",
        "platform": "socrata",
        "endpoint": "https://data.honolulu.gov/resource/msmn-pn2k.json",
        "dataset_id": "msmn-pn2k",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "indianapolis": {
        "name": "Indianapolis",
        "state": "IN",
        "slug": "indianapolis",
        "platform": "socrata",
        "endpoint": "https://data.indy.gov/resource/mna3-bpys.json",
        "dataset_id": "mna3-bpys",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "louisville": {
        "name": "Louisville",
        "state": "KY",
        "slug": "louisville",
        "platform": "socrata",
        "endpoint": "https://data.louisvilleky.gov/resource/5mwi-9d7x.json",
        "dataset_id": "5mwi-9d7x",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "total_value",
            "description": "work_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "memphis": {
        "name": "Memphis",
        "state": "TN",
        "slug": "memphis",
        "platform": "socrata",
        "endpoint": "https://data.memphistn.gov/resource/x2kq-mtik.json",
        "dataset_id": "x2kq-mtik",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "site_address",
            "zip": "zip",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "mesa": {
        "name": "Mesa",
        "state": "AZ",
        "slug": "mesa",
        "platform": "socrata",
        "endpoint": "https://data.mesaaz.gov/resource/qhiu-4p7i.json",
        "dataset_id": "qhiu-4p7i",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "milwaukee": {
        "name": "Milwaukee",
        "state": "WI",
        "slug": "milwaukee",
        "platform": "socrata",
        "endpoint": "https://data.milwaukee.gov/resource/m5j3-78ct.json",
        "dataset_id": "m5j3-78ct",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_class",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "oakland": {
        "name": "Oakland",
        "state": "CA",
        "slug": "oakland",
        "platform": "socrata",
        "endpoint": "https://data.oaklandca.gov/resource/wgz8-438i.json",
        "dataset_id": "wgz8-438i",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "oklahoma_city": {
        "name": "Oklahoma City",
        "state": "OK",
        "slug": "oklahoma-city",
        "platform": "socrata",
        "endpoint": "https://data.okc.gov/resource/5fbs-8qm4.json",
        "dataset_id": "5fbs-8qm4",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "omaha": {
        "name": "Omaha",
        "state": "NE",
        "slug": "omaha",
        "platform": "socrata",
        "endpoint": "https://data.cityofomaha.org/resource/7ggb-3m9q.json",
        "dataset_id": "7ggb-3m9q",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "address",
            "zip": "zip",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "st_louis": {
        "name": "St. Louis",
        "state": "MO",
        "slug": "st-louis",
        "platform": "socrata",
        "endpoint": "https://data.stlouis-mo.gov/resource/dk79-5s6i.json",
        "dataset_id": "dk79-5s6i",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "tucson": {
        "name": "Tucson",
        "state": "AZ",
        "slug": "tucson",
        "platform": "socrata",
        "endpoint": "https://data.tucsonaz.gov/resource/k3bm-77zf.json",
        "dataset_id": "k3bm-77zf",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "long_beach": {
        "name": "Long Beach",
        "state": "CA",
        "slug": "long-beach",
        "platform": "socrata",
        "endpoint": "https://data.longbeach.gov/resource/6yaw-2i7d.json",
        "dataset_id": "6yaw-2i7d",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "address",
            "zip": "zip_code",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "fresno": {
        "name": "Fresno",
        "state": "CA",
        "slug": "fresno",
        "platform": "socrata",
        "endpoint": "https://data.fresno.gov/resource/bqwt-zsqu.json",
        "dataset_id": "bqwt-zsqu",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_class",
            "address": "site_address",
            "zip": "zip_code",
            "owner_name": "owner_name",
            "contact_name": "contractor_name",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # ADDITIONAL ARCGIS CITIES (BATCH 2)
    # =========================================================================

    "las_vegas": {
        "name": "Las Vegas",
        "state": "NV",
        "slug": "las-vegas",
        "platform": "arcgis",
        "endpoint": "https://services.arcgis.com/YseQBnl2jq0lrUV5/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "orlando": {
        "name": "Orlando",
        "state": "FL",
        "slug": "orlando",
        "platform": "arcgis",
        "endpoint": "https://services1.arcgis.com/g8J4NxO28XM3C0Jz/arcgis/rest/services/Permits/FeatureServer/0/query",
        "dataset_id": "Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "tampa": {
        "name": "Tampa",
        "state": "FL",
        "slug": "tampa",
        "platform": "arcgis",
        "endpoint": "https://services1.arcgis.com/7cPJ7dGcKWKjZDsJ/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "SITE_ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "WORK_DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "jacksonville": {
        "name": "Jacksonville",
        "state": "FL",
        "slug": "jacksonville",
        "platform": "arcgis",
        "endpoint": "https://services1.arcgis.com/sSwFpTv9KLqJnHQx/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "virginia_beach": {
        "name": "Virginia Beach",
        "state": "VA",
        "slug": "virginia-beach",
        "platform": "arcgis",
        "endpoint": "https://gismaps.vbgov.com/arcgis/rest/services/Permits/Permits_Building/FeatureServer/0/query",
        "dataset_id": "Permits_Building",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "albuquerque": {
        "name": "Albuquerque",
        "state": "NM",
        "slug": "albuquerque",
        "platform": "arcgis",
        "endpoint": "https://services.arcgis.com/cGZriHEIhLNHPjxH/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUM",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    "cleveland": {
        "name": "Cleveland",
        "state": "OH",
        "slug": "cleveland",
        "platform": "arcgis",
        "endpoint": "https://services5.arcgis.com/tVJg5VG05MfZQJmW/arcgis/rest/services/Building_Permits/FeatureServer/0/query",
        "dataset_id": "Building_Permits",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "PERMIT_NUMBER",
            "permit_type": "PERMIT_TYPE",
            "work_type": "WORK_CLASS",
            "address": "ADDRESS",
            "zip": "ZIP_CODE",
            "owner_name": "OWNER_NAME",
            "contact_name": "CONTRACTOR_NAME",
            "filing_date": "ISSUE_DATE",
            "status": "STATUS",
            "estimated_cost": "VALUATION",
            "description": "DESCRIPTION",
        },
        "date_field": "ISSUE_DATE",
        "date_format": "epoch",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # ADDITIONAL VERIFIED WORKING CITIES
    # =========================================================================

    "roseville": {
        "name": "Roseville",
        "state": "CA",
        "slug": "roseville",
        "platform": "socrata",
        "endpoint": "https://data.roseville.ca.us/resource/buxi-gsvq.json",
        "dataset_id": "buxi-gsvq",
        "description": "Building Permits Issued",
        "field_map": {
            "permit_number": "record_number",
            "permit_type": "record_type",
            "work_type": "record_group",
            "address": "",
            "zip": "",
            "filing_date": "issued_date",
            "status": "",
            "estimated_cost": "job_value",
            "description": "record_type",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": False,
        "notes": "No address data in dataset - not useful for leads",
    },

    "marin_county": {
        "name": "Marin County",
        "state": "CA",
        "slug": "marin-county",
        "platform": "socrata",
        "endpoint": "https://data.marincounty.gov/resource/mkbn-caye.json",
        "dataset_id": "mkbn-caye",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_description",
            "address": "address",
            "zip": "zipcode",
            "city": "city_town",
            "filing_date": "issued_date",
            "status": "status",
            "estimated_cost": "construction_value",
            "description": "work_description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "gainesville": {
        "name": "Gainesville",
        "state": "FL",
        "slug": "gainesville",
        "platform": "socrata",
        "endpoint": "https://data.cityofgainesville.org/resource/p798-x3nx.json",
        "dataset_id": "p798-x3nx",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit",
            "permit_type": "permit_type",
            "work_type": "permit_type",
            "address": "address",
            "zip": "zip",
            "contact_name": "contractor",
            "filing_date": "issue",
            "status": "status",
            "estimated_cost": "value",
            "description": "description",
        },
        "date_field": "issue",
        "limit": 2000,
        "active": True,
    },

    "mesa_new": {
        "name": "Mesa",
        "state": "AZ",
        "slug": "mesa",
        "platform": "socrata",
        "endpoint": "https://citydata.mesaaz.gov/resource/dzpk-hxfb.json",
        "dataset_id": "dzpk-hxfb",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "property_address",
            "zip": "zip_code",
            "filing_date": "issued_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "corona": {
        "name": "Corona",
        "state": "CA",
        "slug": "corona",
        "platform": "socrata",
        "endpoint": "https://corstat.coronaca.gov/resource/2agx-camz.json",
        "dataset_id": "2agx-camz",
        "description": "CorStat Building Permits",
        "field_map": {
            "permit_number": "permit_no",
            "permit_type": "permittype",
            "work_type": "permitsubtype",
            "address": "site_addr",
            "zip": "zip",
            "filing_date": "issued",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "permitsubtype",
        },
        "date_field": "issued",
        "limit": 2000,
        "active": True,
    },

    "montgomery_county_md": {
        "name": "Montgomery County",
        "state": "MD",
        "slug": "montgomery-county-md",
        "platform": "socrata",
        "endpoint": "https://data.montgomerycountymd.gov/resource/qxie-8qnp.json",
        "dataset_id": "qxie-8qnp",
        "description": "Electrical Building Permits",
        "field_map": {
            "permit_number": "permitno",
            "permit_type": "worktype",
            "work_type": "worktype",
            "address": "stname",
            "zip": "zip",
            "city": "city",
            "filing_date": "issueddate",
            "status": "status",
            "estimated_cost": "fee",
            "description": "usecode",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "williamson_county_tx": {
        "name": "Williamson County",
        "state": "TX",
        "slug": "williamson-county-tx",
        "platform": "socrata",
        "endpoint": "https://data.wcad.org/resource/fqhf-gyjx.json",
        "dataset_id": "fqhf-gyjx",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "comment",
            "work_type": "comment",
            "address": "situsaddress",
            "filing_date": "issuedate",
            "status": "status",
            "estimated_cost": "value",
            "description": "comment",
        },
        "date_field": "issuedate",
        "limit": 2000,
        "active": True,
    },

    "dallas_verified": {
        "name": "Dallas",
        "state": "TX",
        "slug": "dallas",
        "platform": "socrata",
        "endpoint": "https://www.dallasopendata.com/resource/e7gq-4sah.json",
        "dataset_id": "e7gq-4sah",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "land_use",
            "address": "street_address",
            "contact_name": "contractor",
            "filing_date": "issued_date",
            "status": "status",
            "estimated_cost": "value",
            "description": "work_description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "framingham": {
        "name": "Framingham",
        "state": "MA",
        "slug": "framingham",
        "platform": "socrata",
        "endpoint": "https://data.framinghamma.gov/resource/2vzw-yean.json",
        "dataset_id": "2vzw-yean",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permit",
            "permit_type": "type",
            "work_type": "sub_type",
            "address": "street_name",
            "filing_date": "applied",
            "status": "category",
            "estimated_cost": "estimated_job_cost",
            "description": "description",
        },
        "date_field": "applied",
        "limit": 2000,
        "active": True,
    },

    "parker": {
        "name": "Parker",
        "state": "CO",
        "slug": "parker",
        "platform": "socrata",
        "endpoint": "https://parkeronline.data.socrata.com/resource/f6vi-7y2m.json",
        "dataset_id": "f6vi-7y2m",
        "description": "Parker Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_job_type",
            "work_type": "construction_category",
            "address": "original_address_1",
            "city": "original_city",
            "filing_date": "issued_date",
            "status": "status_current",
            "estimated_cost": "total_project_valuation",
            "description": "description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "albany": {
        "name": "Albany",
        "state": "NY",
        "slug": "albany",
        "platform": "socrata",
        "endpoint": "https://data.ny.gov/resource/kb9s-4gzd.json",
        "dataset_id": "kb9s-4gzd",
        "description": "City of Albany Building Permits Issued",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_type",
            "address": "address",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "date",
            "status": "status",
            "estimated_cost": "estimated_cost",
            "description": "description_of_work",
        },
        "date_field": "date",
        "limit": 2000,
        "active": True,
        "notes": "Historical data 2009-2013",
    },

    "prince_georges_county": {
        "name": "Prince Georges County",
        "state": "MD",
        "slug": "prince-georges-county",
        "platform": "socrata",
        "endpoint": "https://data.princegeorgescountymd.gov/resource/weik-ttee.json",
        "dataset_id": "weik-ttee",
        "description": "Residential and Commercial Permits",
        "field_map": {
            "permit_number": "permit_case_id",
            "permit_type": "permit_type",
            "work_type": "permit_category",
            "address": "street_address",
            "city": "city",
            "filing_date": "permit_issued_date",
            "status": "permit_status",
            "estimated_cost": "cost",
            "description": "case_name",
        },
        "date_field": "permit_issued_date",
        "limit": 2000,
        "active": True,
    },

    "new_jersey_state": {
        "name": "New Jersey",
        "state": "NJ",
        "slug": "new-jersey",
        "platform": "socrata",
        "endpoint": "https://data.nj.gov/resource/w9se-dmra.json",
        "dataset_id": "w9se-dmra",
        "description": "NJ Construction Permit Data (Statewide)",
        "field_map": {
            "permit_number": "recordid",
            "permit_type": "consttype",
            "work_type": "consttype",
            "address": "block",
            "city": "muniname",
            "filing_date": "yrmo",
            "status": "status",
            "estimated_cost": "constcost",
            "description": "usegroup",
        },
        "date_field": "yrmo",
        "limit": 2000,
        "active": True,
        "notes": "Statewide NJ data - covers Newark, Jersey City, Trenton, etc.",
    },

    "howard_county": {
        "name": "Howard County",
        "state": "MD",
        "slug": "howard-county",
        "platform": "socrata",
        "endpoint": "https://opendata.howardcountymd.gov/resource/kvz2-j5cj.json",
        "dataset_id": "kvz2-j5cj",
        "description": "Building, Electrical, Fire, Grading Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "type",
            "work_type": "category",
            "address": "address",
            "city": "city",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "cost",
            "description": "permit_type",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "sonoma_county": {
        "name": "Sonoma County",
        "state": "CA",
        "slug": "sonoma-county",
        "platform": "socrata",
        "endpoint": "https://data.sonomacounty.ca.gov/resource/652y-5ihx.json",
        "dataset_id": "652y-5ihx",
        "description": "Sonoma County Rebuilding Permits",
        "field_map": {
            "permit_number": "record_id",
            "permit_type": "record_type",
            "work_type": "category",
            "address": "address",
            "filing_date": "date_opened",
            "status": "permit_status",
            "estimated_cost": "valuation",
            "description": "permit_description",
        },
        "date_field": "date_opened",
        "limit": 2000,
        "active": True,
    },

    "collin_county": {
        "name": "Collin County",
        "state": "TX",
        "slug": "collin-county",
        "platform": "socrata",
        "endpoint": "https://data.texas.gov/resource/82ee-gbj5.json",
        "dataset_id": "82ee-gbj5",
        "description": "Collin CAD Building Permits",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "permittypedescr",
            "work_type": "permittypecode",
            "address": "situsaddress",
            "filing_date": "permitissueddate",
            "status": "status",
            "estimated_cost": "permitvalue",
            "description": "permittypedescr",
        },
        "date_field": "permitissueddate",
        "limit": 2000,
        "active": True,
    },

    "summit_county_ut": {
        "name": "Summit County",
        "state": "UT",
        "slug": "summit-county-ut",
        "platform": "socrata",
        "endpoint": "https://opendata.utah.gov/resource/rtmz-aq9t.json",
        "dataset_id": "rtmz-aq9t",
        "description": "Summit County Building Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "permit_description",
            "work_type": "permit_description",
            "address": "situsaddress",
            "contact_name": "contractor",
            "filing_date": "permitdate",
            "status": "status",
            "estimated_cost": "value",
            "description": "permit_description",
        },
        "date_field": "permitdate",
        "limit": 2000,
        "active": True,
    },

    "west_hollywood": {
        "name": "West Hollywood",
        "state": "CA",
        "slug": "west-hollywood",
        "platform": "socrata",
        "endpoint": "https://data.weho.org/resource/d96h-4b7t.json",
        "dataset_id": "d96h-4b7t",
        "description": "Construction Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "scope_of_work",
            "work_type": "scope_of_work",
            "address": "location_description",
            "filing_date": "date",
            "status": "status",
            "description": "scope_of_work",
        },
        "date_field": "date",
        "limit": 2000,
        "active": True,
    },

    "calgary": {
        "name": "Calgary",
        "state": "AB",
        "slug": "calgary",
        "platform": "socrata",
        "endpoint": "https://data.calgary.ca/resource/c2es-76ed.json",
        "dataset_id": "c2es-76ed",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "permittype",
            "work_type": "permitclassmapped",
            "address": "communityname",
            "filing_date": "issueddate",
            "status": "statuscurrent",
            "estimated_cost": "estprojectcost",
            "description": "workclassmapped",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
        "notes": "Calgary, Alberta, Canada",
    },

    "orlando_new": {
        "name": "Orlando",
        "state": "FL",
        "slug": "orlando",
        "platform": "socrata",
        "endpoint": "https://data.cityoforlando.net/resource/ryhf-m453.json",
        "dataset_id": "ryhf-m453",
        "description": "Permit Applications",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "application_type",
            "work_type": "worktype",
            "address": "permit_address",
            "owner_name": "property_owner_name",
            "contact_name": "contractor_name",
            "filing_date": "permit_issued_date",
            "status": "permit_status",
            "estimated_cost": "total_value",
            "description": "permit_description",
        },
        "date_field": "permit_issued_date",
        "limit": 2000,
        "active": True,
    },

    "somerville": {
        "name": "Somerville",
        "state": "MA",
        "slug": "somerville",
        "platform": "socrata",
        "endpoint": "https://data.somervillema.gov/resource/vxgw-vmky.json",
        "dataset_id": "vxgw-vmky",
        "description": "Permits",
        "field_map": {
            "permit_number": "id",
            "permit_type": "type",
            "work_type": "type",
            "address": "address",
            "filing_date": "application_date",
            "status": "status",
            "estimated_cost": "amount",
            "description": "description",
        },
        "date_field": "application_date",
        "limit": 2000,
        "active": True,
    },

    "norfolk_new": {
        "name": "Norfolk",
        "state": "VA",
        "slug": "norfolk",
        "platform": "socrata",
        "endpoint": "https://data.norfolk.gov/resource/bnrb-u445.json",
        "dataset_id": "bnrb-u445",
        "description": "Permits and Inspections",
        "field_map": {
            "permit_number": "inspection_number",
            "permit_type": "inspection_type",
            "work_type": "inspection_group",
            "address": "permit_address",
            "filing_date": "inspection_date",
            "status": "inspection_status",
            "description": "permit_description",
        },
        "date_field": "inspection_date",
        "limit": 2000,
        "active": True,
    },

    "frederick": {
        "name": "Frederick",
        "state": "MD",
        "slug": "frederick",
        "platform": "socrata",
        "endpoint": "https://opendata.maryland.gov/resource/xrz3-9xhj.json",
        "dataset_id": "xrz3-9xhj",
        "description": "City of Frederick Issued Permits",
        "field_map": {
            "permit_number": "permit_no",
            "permit_type": "classification",
            "work_type": "classification",
            "address": "address",
            "owner_name": "owner",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "classification",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "college_station": {
        "name": "College Station",
        "state": "TX",
        "slug": "college-station",
        "platform": "socrata",
        "endpoint": "https://data.cstx.gov/resource/hrbn-znt6.json",
        "dataset_id": "hrbn-znt6",
        "description": "Permits Master Dataset",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_subtype",
            "address": "address",
            "filing_date": "issued_date",
            "status": "permit_status",
            "estimated_cost": "valuation",
            "description": "permit_description",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "cook_county": {
        "name": "Cook County",
        "state": "IL",
        "slug": "cook-county",
        "platform": "socrata",
        "endpoint": "https://datacatalog.cookcountyil.gov/resource/6yjf-dfxs.json",
        "dataset_id": "6yjf-dfxs",
        "description": "Assessor Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_type",
            "address": "address",
            "filing_date": "date_issued",
            "status": "status",
            "estimated_cost": "amount",
            "description": "description",
        },
        "date_field": "date_issued",
        "limit": 2000,
        "active": True,
    },

    "bloomington_in": {
        "name": "Bloomington",
        "state": "IN",
        "slug": "bloomington-in",
        "platform": "socrata",
        "endpoint": "https://data.bloomington.in.gov/resource/9q6j-a8rc.json",
        "dataset_id": "9q6j-a8rc",
        "description": "Rental Permits",
        "field_map": {
            "permit_number": "permit_num",
            "permit_type": "contact_type",
            "work_type": "contact_type",
            "address": "property_address",
            "contact_name": "contact_name",
            "filing_date": "issue_date",
            "status": "status",
            "description": "description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "asotin": {
        "name": "Asotin",
        "state": "WA",
        "slug": "asotin",
        "platform": "socrata",
        "endpoint": "https://data.wa.gov/resource/ez9k-2c5k.json",
        "dataset_id": "ez9k-2c5k",
        "description": "City of Asotin Building Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "typeofpermit",
            "work_type": "typeofpermit",
            "address": "address",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issueddate",
            "status": "status",
            "estimated_cost": "value",
            "description": "typeofpermit",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "honolulu_verified": {
        "name": "Honolulu",
        "state": "HI",
        "slug": "honolulu",
        "platform": "socrata",
        "endpoint": "https://data.honolulu.gov/resource/4vab-c87q.json",
        "dataset_id": "4vab-c87q",
        "description": "Building Permits",
        "field_map": {
            "permit_number": "buildingpermitno",
            "permit_type": "permittype",
            "work_type": "permittype",
            "address": "tmk",
            "contact_name": "contractor",
            "filing_date": "issueddate",
            "status": "status",
            "estimated_cost": "acceptedvalue",
            "description": "jobdescription",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "nola_verified": {
        "name": "New Orleans",
        "state": "LA",
        "slug": "new-orleans",
        "platform": "socrata",
        "endpoint": "https://data.nola.gov/resource/rcm3-fn58.json",
        "dataset_id": "rcm3-fn58",
        "description": "Permits",
        "field_map": {
            "permit_number": "numstring",
            "permit_type": "type",
            "work_type": "code",
            "address": "address",
            "owner_name": "owner",
            "filing_date": "issueddate",
            "status": "isclosed",
            "description": "division",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "edmonton": {
        "name": "Edmonton",
        "state": "AB",
        "slug": "edmonton",
        "platform": "socrata",
        "endpoint": "https://data.edmonton.ca/resource/24uj-dj8v.json",
        "dataset_id": "24uj-dj8v",
        "description": "General Building Permits",
        "field_map": {
            "permit_number": "row_id",
            "permit_type": "job_category",
            "work_type": "building_type",
            "address": "neighbourhood_name",
            "filing_date": "issue_date",
            "status": "count",
            "estimated_cost": "construction_value",
            "description": "job_description",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
        "notes": "Edmonton, Alberta, Canada",
    },

    "winnipeg": {
        "name": "Winnipeg",
        "state": "MB",
        "slug": "winnipeg",
        "platform": "socrata",
        "endpoint": "https://data.winnipeg.ca/resource/it4w-cpf4.json",
        "dataset_id": "it4w-cpf4",
        "description": "Detailed Building Permit Data",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "work_type",
            "address": "street_name",
            "filing_date": "issue_date",
            "status": "sub_type",
            "estimated_cost": "value",
            "description": "permit_group",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
        "notes": "Winnipeg, Manitoba, Canada",
    },

    "kansas_city_historical": {
        "name": "Kansas City",
        "state": "MO",
        "slug": "kansas-city",
        "platform": "socrata",
        "endpoint": "https://data.kcmo.org/resource/cvnj-fvgf.json",
        "dataset_id": "cvnj-fvgf",
        "description": "2000-2009 Building Permit Listing",
        "field_map": {
            "permit_number": "number",
            "permit_type": "res_non",
            "work_type": "res_non",
            "address": "name",
            "filing_date": "year",
            "status": "status",
            "description": "prefix",
        },
        "date_field": "year",
        "limit": 2000,
        "active": True,
        "notes": "Historical data 2000-2009",
    },

    "little_rock": {
        "name": "Little Rock",
        "state": "AR",
        "slug": "little-rock",
        "platform": "socrata",
        "endpoint": "https://data.littlerock.gov/resource/mkfu-qap3.json",
        "dataset_id": "mkfu-qap3",
        "description": "Planning and Development Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "permittype",
            "work_type": "workclass",
            "address": "propertyaddress",
            "city": "propertycity",
            "zip": "propertyzip",
            "contact_name": "contractor",
            "filing_date": "permitissuedate",
            "status": "permitstatus",
            "estimated_cost": "declvltn",
            "description": "projectdesc",
        },
        "date_field": "permitissuedate",
        "limit": 2000,
        "active": True,
    },

    "urbana": {
        "name": "Urbana",
        "state": "IL",
        "slug": "urbana",
        "platform": "socrata",
        "endpoint": "https://illinois-edp.data.socrata.com/resource/dvw9-7wyx.json",
        "dataset_id": "dvw9-7wyx",
        "description": "Community Development Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "improvement_type",
            "address": "address",
            "contact_name": "applicant",
            "filing_date": "issue_date",
            "status": "permit_status",
            "estimated_cost": "fee_amount",
            "description": "permit_type",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "salt_lake_city": {
        "name": "Salt Lake City",
        "state": "UT",
        "slug": "salt-lake-city",
        "platform": "socrata",
        "endpoint": "https://opendata.utah.gov/resource/nbv6-7v56.json",
        "dataset_id": "nbv6-7v56",
        "description": "Salt Lake City Building Permits",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "grouptype",
            "work_type": "groupsubtype",
            "address": "projecthousenbr",
            "street": "projectstreetname",
            "zip": "zipcode",
            "filing_date": "applicationdate",
            "status": "applicationstatus",
            "estimated_cost": "total_fee",
            "description": "workdescription",
        },
        "date_field": "applicationdate",
        "limit": 2000,
        "active": True,
    },

    "clarkston": {
        "name": "Clarkston",
        "state": "WA",
        "slug": "clarkston",
        "platform": "socrata",
        "endpoint": "https://data.wa.gov/resource/uxv9-c2g9.json",
        "dataset_id": "uxv9-c2g9",
        "description": "City of Clarkston Building Permits",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "type_of_construction",
            "work_type": "type_of_construction",
            "address": "site_address",
            "owner_name": "owner_name",
            "filing_date": "permit_date",
            "status": "status",
            "estimated_cost": "valuation",
            "description": "type_of_construction",
        },
        "date_field": "permit_date",
        "limit": 2000,
        "active": True,
    },

    "auburn_wa": {
        "name": "Auburn",
        "state": "WA",
        "slug": "auburn",
        "platform": "socrata",
        "endpoint": "https://data.auburnwa.gov/resource/fted-8bve.json",
        "dataset_id": "fted-8bve",
        "description": "City of Auburn Permits",
        "field_map": {
            "permit_number": "permit",
            "permit_type": "type",
            "work_type": "subtype",
            "address": "address",
            "owner_name": "owner",
            "contact_name": "contractor",
            "filing_date": "issued",
            "status": "status",
            "description": "description",
        },
        "date_field": "issued",
        "limit": 2000,
        "active": True,
    },

    "dumfries": {
        "name": "Dumfries",
        "state": "VA",
        "slug": "dumfries",
        "platform": "socrata",
        "endpoint": "https://data.dumfriesva.gov/resource/76tz-5d55.json",
        "dataset_id": "76tz-5d55",
        "description": "Town Permit Processing",
        "field_map": {
            "permit_number": "permit_number",
            "permit_type": "permit_type",
            "work_type": "permit_type",
            "address": "location",
            "filing_date": "issued_date",
            "status": "fiscal_year",
            "description": "permit_type",
        },
        "date_field": "issued_date",
        "limit": 2000,
        "active": True,
    },

    "pierce_county": {
        "name": "Pierce County",
        "state": "WA",
        "slug": "pierce-county",
        "platform": "socrata",
        "endpoint": "https://open.piercecountywa.gov/resource/rcj9-mkn4.json",
        "dataset_id": "rcj9-mkn4",
        "description": "Pierce County Building Permits",
        "field_map": {
            "permit_number": "applicationnumber",
            "permit_type": "applicationtype",
            "work_type": "worktype",
            "address": "siteaddress",
            "filing_date": "issueddate",
            "status": "applicationstatus",
            "estimated_cost": "buildingvaluation",
            "description": "workdescription",
        },
        "date_field": "issueddate",
        "limit": 2000,
        "active": True,
    },

    "cambridge": {
        "name": "Cambridge",
        "state": "MA",
        "slug": "cambridge",
        "platform": "socrata",
        "endpoint": "https://data.cambridgema.gov/resource/9qm7-wbdc.json",
        "dataset_id": "9qm7-wbdc",
        "description": "Building Permits: New Construction",
        "field_map": {
            "permit_number": "id",
            "permit_type": "permit_type",
            "work_type": "construction_type",
            "address": "full_address",
            "filing_date": "issue_date",
            "status": "status",
            "estimated_cost": "building_cost",
            "description": "description_of_work",
        },
        "date_field": "issue_date",
        "limit": 2000,
        "active": True,
    },

    "nola_blds": {
        "name": "New Orleans",
        "state": "LA",
        "slug": "new-orleans",
        "platform": "socrata",
        "endpoint": "https://data.nola.gov/resource/72f9-bi28.json",
        "dataset_id": "72f9-bi28",
        "description": "Permits - BLDS",
        "field_map": {
            "permit_number": "permitnum",
            "permit_type": "permittype",
            "work_type": "workclass",
            "address": "originaladdress1",
            "city": "originalcity",
            "zip": "originalzip",
            "filing_date": "issuedate",
            "status": "statuscurrent",
            "estimated_cost": "estprojectcost",
            "description": "description",
        },
        "date_field": "issuedate",
        "limit": 2000,
        "active": True,
        "notes": "Better dataset with more fields",
    },

    "henderson_nv": {
        "name": "Henderson",
        "state": "NV",
        "slug": "henderson",
        "platform": "socrata",
        "endpoint": "https://performance.cityofhenderson.com/resource/fpc9-568j.json",
        "dataset_id": "fpc9-568j",
        "description": "City of Henderson Permits",
        "field_map": {
            "permit_number": "permitnumber",
            "permit_type": "permittype",
            "work_type": "workclass",
            "address": "locationdescription",
            "owner_name": "ownername",
            "contact_name": "professionalname",
            "filing_date": "applydate",
            "status": "permitstatus",
            "estimated_cost": "valuationtotal",
            "description": "permitdescription",
        },
        "date_field": "applydate",
        "limit": 2000,
        "active": True,
    },

    # =========================================================================
    # INACTIVE / PENDING CITIES
    # =========================================================================

    "dallas": {
        "name": "Dallas",
        "state": "TX",
        "slug": "dallas",
        "platform": "socrata",
        "endpoint": "",
        "dataset_id": "",
        "description": "Building Permits - Pending API availability",
        "field_map": {},
        "date_field": "",
        "limit": 2000,
        "active": False,
        "notes": "Dallas open data portal needs further investigation for permit API",
    },

    "houston": {
        "name": "Houston",
        "state": "TX",
        "slug": "houston",
        "platform": "ckan",
        "endpoint": "",
        "dataset_id": "",
        "description": "Building Permits - Aggregate data only",
        "field_map": {},
        "date_field": "",
        "limit": 2000,
        "active": False,
        "notes": "Houston provides aggregated monthly data, not individual permits",
    },

    "minneapolis": {
        "name": "Minneapolis",
        "state": "MN",
        "slug": "minneapolis",
        "platform": "socrata",
        "endpoint": "",
        "dataset_id": "",
        "description": "Building Permits - Pending API availability",
        "field_map": {},
        "date_field": "",
        "limit": 2000,
        "active": False,
        "notes": "Minneapolis data may be regional (Twin Cities area)",
    },
}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_active_cities():
    """Return list of active city keys."""
    return [k for k, v in CITY_REGISTRY.items() if v.get("active", False)]


def get_city_config(city_key):
    """Get configuration for a specific city."""
    return CITY_REGISTRY.get(city_key)


def get_cities_by_platform(platform):
    """Get all active cities for a specific platform."""
    return [k for k, v in CITY_REGISTRY.items()
            if v.get("platform") == platform and v.get("active", False)]


def get_city_count():
    """Get count of active cities."""
    return len(get_active_cities())


def get_city_by_slug(slug):
    """Find city config by its URL slug."""
    for key, config in CITY_REGISTRY.items():
        if config.get("slug") == slug:
            return key, config
    return None, None


def get_all_cities_info():
    """Get basic info for all active cities (for display purposes)."""
    cities = []
    for key, config in CITY_REGISTRY.items():
        if config.get("active", False):
            cities.append({
                "key": key,
                "name": config["name"],
                "state": config["state"],
                "slug": config["slug"],
                "platform": config["platform"],
            })
    return sorted(cities, key=lambda x: x["name"])


# Trade classification keywords (moved from config.py for consolidation)
TRADE_CATEGORIES = {
    "Roofing": [
        "roof", "roofing", "shingle", "membrane", "flashing", "gutter",
        "soffit", "fascia", "re-roof", "reroof"
    ],
    "HVAC": [
        "hvac", "heating", "cooling", "air condition", "furnace", "boiler",
        "ductwork", "ventilation", "heat pump", "ac unit", "a/c", "mini split",
        "thermostat", "refriger"
    ],
    "Electrical": [
        "electric", "wiring", "panel", "circuit", "outlet", "lighting",
        "solar", "photovoltaic", "pv system", "ev charger", "generator",
        "transformer", "switchgear"
    ],
    "Plumbing": [
        "plumb", "pipe", "sewer", "drain", "water heater", "fixture",
        "backflow", "septic", "gas line", "water line", "sprinkler"
    ],
    "General Construction": [
        "new building", "new construction", "addition", "alteration",
        "renovation", "remodel", "tenant improvement", "build out",
        "commercial build", "residential build", "foundation"
    ],
    "Demolition": [
        "demolition", "demo", "tear down", "abatement", "asbestos",
        "hazmat", "deconstruct"
    ],
    "Interior Renovation": [
        "interior", "kitchen", "bathroom", "flooring", "drywall",
        "painting", "cabinet", "countertop", "tile", "finish"
    ],
    "Windows & Doors": [
        "window", "door", "glazing", "storefront", "curtain wall",
        "skylight", "glass"
    ],
    "Structural": [
        "structural", "beam", "column", "load bearing", "seismic",
        "retrofit", "reinforc", "steel", "concrete"
    ],
    "Landscaping & Exterior": [
        "landscape", "fence", "deck", "patio", "retaining wall",
        "pool", "spa", "pergola", "awning", "carport", "garage"
    ],
}

# Value tiers for lead scoring
PERMIT_VALUE_TIERS = {
    "high": {
        "min_cost": 50000,
        "label": "High Value",
        "color": "#e74c3c",
    },
    "medium": {
        "min_cost": 10000,
        "label": "Medium Value",
        "color": "#f39c12",
    },
    "low": {
        "min_cost": 0,
        "label": "Standard",
        "color": "#27ae60",
    },
}
